-- Second catalogue batch: 17 products from the remaining supplied photos.
-- Safe to re-run: each row is skipped if a product with that name already exists.
-- Paste into Supabase -> SQL Editor -> Run.

insert into products
  (name, tagline, description, price, compare_at, image, category, badge,
   stock, size, skin_type, benefits, how_to_use, featured, bestseller, reviews)
select v.* from (values
  ('NYX Poudre à Lèvres Lip Duo', 'Matte Powder Lip Colour', 'A weightless powder-matte lip colour that sets soft rather than dry, and layers under gloss without going patchy. Paired here with the jelly gloss for a full lip look.', 13, null, '/products/nyx-poudre.jpg', 'Lips', null, 16, '6 ml', 'All lip types', 'Powder-matte finish · Comfortable, non-drying wear · Layers under gloss · Buildable colour', 'Apply from the centre of the lip outward. Layer for depth, or top with gloss.', false, false, 0),
  ('Labello Glowy Lips Berry & Cherry', 'Tinted Balm, Two Shades', 'The Glowy Lips balm in Berry and Cherry. Hyaluronic acid, vitamin E and shea butter support the lips'' own renewal while a sheer tint adds colour and a soft shine.', 7, null, '/products/labello-glowy-duo.jpg', 'Lips', null, 26, '4.8 g', 'Dry and sensitive lips', '24h moisture · Hyaluronic acid, vitamin E and shea butter · Natural ingredients · Sheer berry or cherry tint', 'Apply whenever lips feel dry. Reapply through the day for more colour.', false, false, 0),
  ('Labello Disney Ariel Watermelon Shine', 'Limited Disney Edition', 'The Little Mermaid edition of Labello''s tinted care balm, in a sheer watermelon shine. Holds a 72-hour moisture balance and comes in collectible Disney Princess packaging.', 6, null, '/products/labello-ariel.jpg', 'Lips', 'Limited', 14, '4.8 g', 'All lip types', '72h moisture balance · Sheer watermelon tint · Collectible Disney edition', 'Apply generously whenever lips need moisture.', false, false, 0),
  ('Labello Disney Mulan Cherry Shine', 'Limited Disney Edition', 'The Mulan edition of Labello''s tinted care balm in a soft cherry shine. Same 72-hour moisture balance, in collectible Disney Princess packaging.', 6, null, '/products/labello-mulan.jpg', 'Lips', 'Limited', 14, '4.8 g', 'All lip types', '72h moisture balance · Sheer cherry tint · Collectible Disney edition', 'Apply generously whenever lips need moisture.', false, false, 0),
  ('Schaebens Dead Sea Mud Mask', 'Deep Clean for Congested Skin', 'A Dead Sea mud mask with algae, zinc and minerals that draws out congestion and cleans deeply. Reduces skin oil by up to 38 percent, and works on spots and blackheads. Vegan.', 4, null, '/products/schaebens-mud.jpg', 'Skincare', null, 30, '2 × 5 ml', 'Oily and blemish-prone skin', 'Up to 38% less skin oil · Dead Sea mud, algae, zinc and minerals · Targets spots and blackheads · Vegan', 'Spread over cleansed skin, avoiding the eyes. Leave 10 minutes, then rinse warm.', false, false, 0),
  ('Schaebens Aloe Vera Sheet Mask', 'Regeneration Booster', 'An aloe vera sheet mask with glycerin and hyaluronic acid that refreshes on contact and calms redness and irritation. Up to 175 percent more moisture, on a biodegradable cloth.', 3, null, '/products/schaebens-aloe.jpg', 'Skincare', null, 28, '1 sheet mask', 'All skin types', 'Up to 175% more moisture · Calms redness and irritation · Aloe vera, glycerin, hyaluronic acid · Biodegradable cloth', 'Smooth onto cleansed skin, leave 15 minutes, then massage in what remains.', false, false, 0),
  ('Schaebens Vitamin C Sheet Mask', 'Glow Booster', 'A vitamin C sheet mask with vitamin B3 and hyaluronic acid for skin that has gone dull. Softens the look of lines by up to 80 percent while restoring moisture. Vegan.', 3, null, '/products/schaebens-vitc.jpg', 'Skincare', null, 26, '1 sheet mask', 'Dull and demanding skin', 'Up to 80% reduced line volume · Vitamin C, vitamin B3, hyaluronic acid · Restores moisture · Vegan', 'Smooth onto cleansed skin, leave 15 minutes, then massage in what remains.', false, false, 0),
  ('Schaebens Moisture Mask', '48-Hour Hydration', 'A cucumber, urea and thermal water sheet mask for skin that feels tight. Holds up to 48 hours of moisture with an effect you can feel straight away. Tested over four weeks.', 3, null, '/products/schaebens-moisture.jpg', 'Skincare', null, 26, '1 sheet mask', 'Dry skin', 'Up to 48h more moisture · Cucumber, urea and thermal water · Immediate effect · Dermatologically confirmed', 'Smooth onto cleansed skin, leave 15 minutes, then massage in what remains.', false, false, 0),
  ('SOME BY MI Real Snail Mask', 'Skin Barrier Care', 'A plant-based biodegradable sheet mask with real snail mucin, formulated to strengthen the skin barrier and soothe it against outside irritants. Dermatologist tested.', 4, null, '/products/somebymi-snail.jpg', 'Skincare', null, 24, '20 g', 'Sensitive and irritated skin', 'Strengthens the skin barrier · Soothing and moisturising · Real snail mucin · 100% plant-based biodegradable sheet', 'Apply to cleansed skin, leave 15 to 20 minutes, then pat in the remaining essence.', false, false, 0),
  ('SOME BY MI Real Matcha Pore Mask', 'Pore & Oil Control', 'A plant-based sheet mask rich in matcha tannins, which naturally tighten the look of enlarged pores and help balance oil and moisture. Dermatologist tested.', 4, null, '/products/somebymi-matcha.jpg', 'Skincare', null, 22, '20 g', 'Oily and combination skin', 'Reduces the appearance of enlarged pores · Balances oil and moisture · Real matcha · 100% plant-based biodegradable sheet', 'Apply to cleansed skin, leave 15 to 20 minutes, then pat in the remaining essence.', false, false, 0),
  ('Garnier Hydra Bomb Sheet Mask', 'A Serum''s Worth of Hydration', 'A tissue mask holding the equivalent of a full bottle of serum, with hyaluronic acid and grape seed extract. Intensely hydrating, smoothing and plumping in 15 minutes. Vegan.', 4, null, '/products/garnier-hydra-bomb.jpg', 'Skincare', null, 25, '1 tissue mask', 'All skin types, first signs of ageing', 'Equivalent of one bottle of serum · Hyaluronic acid and grape seed extract · Smoothing and plumping · Vegan formula, compostable cloth', 'Unfold onto cleansed skin, leave 15 minutes, then massage in the remaining serum.', false, false, 0),
  ('Garnier Salicylic Serum Mask', 'Anti-Blemish Treatment', 'A salicylic acid serum mask soaked in the equivalent of half a bottle of serum. Reduces imperfections by up to 48 percent and is gentle enough for sensitive skin.', 4, null, '/products/garnier-salicylic.jpg', 'Skincare', null, 25, '1 tissue mask', 'Blemish-prone and sensitive skin', 'Up to 48% fewer imperfections · With salicylic acid · Suitable for sensitive skin · Dermatologically tested', 'Unfold onto cleansed skin, leave 15 minutes, then massage in the remaining serum.', false, false, 0),
  ('MISSHA Airy Fit Aloe Sheet Mask', 'Korean Water-Essence Mask', 'A close-fitting Korean sheet mask soaked in a light water essence, with aloe for straightforward moisture and comfort. Skin-irritation tested.', 3, null, '/products/missha-aloe.jpg', 'Skincare', null, 20, '19 g', 'All skin types', 'Light water-essence formula · Close-fitting airy sheet · Aloe for moisture and comfort · Skin-irritation tested', 'Apply to cleansed skin, leave 15 to 20 minutes, then pat in what remains.', false, false, 0),
  ('YEAUTY Avocado Cucumber Mask', 'Niacinamide Smoothie Serum', 'A second-skin sheet mask with avocado, cucumber and niacinamide in a smoothie-textured serum. Intensive moisture with a 3D fit that stays put while you move.', 4, null, '/products/yeauty-avocado.jpg', 'Skincare', null, 22, '1 sheet mask', 'All skin types', 'Avocado, cucumber and niacinamide · 3D second-skin fit · Intensive moisture · Smoothie serum texture', 'Apply to cleansed skin, leave 15 to 20 minutes, then pat in what remains.', false, false, 0),
  ('Real Deep Glass Skin Mask Pink PDRN', 'Hydrogel Glow Mask', 'A one-piece hydrogel mask with pink PDRN for an intense glow. Sits close to the skin and works in 60 minutes. Suits all skin types.', 6, null, '/products/glass-skin-pdrn.jpg', 'Skincare', 'New', 15, '1 hydrogel mask', 'All skin types', 'Intense glow · Pink PDRN · One-piece hydrogel · Works in 60 minutes', 'Apply both halves to cleansed skin, leave up to 60 minutes, then pat in what remains.', false, false, 0),
  ('Nø Cosmetics Travel Set', 'Five-Piece Skin Starter', 'A clear zip pouch holding five Nø Cosmetics minis: daily facial mist, SPF 30 day cream, re-balance cream cleanser, base hydration cream and a peach body cleanser. A whole routine in cabin-bag sizes.', 24, 29, '/products/no-cosmetics-set.jpg', 'Skincare', 'Gift Set', 10, '5-piece travel set', 'All skin types', 'Complete routine in travel sizes · SPF 30 UVA and UVB protection · Gentle cream cleanser · Reusable clear pouch', 'Cleanse, mist, then day cream with SPF in the morning and hydration cream at night.', true, false, 0),
  ('Body & Soul Slow Down Gift Set', 'Peony & Vanilla, Three Pieces', 'Body spray, hand cream and shower gel in the Pink scent — peony and vanilla, meant to slow the day down. Arrives in its own gift bag, ready to give.', 18, 22, '/products/body-soul-set.jpg', 'Body', 'Gift Set', 12, '3-piece set', 'All skin types', 'Relaxes and calms · Peony and vanilla scent · Body spray, hand cream and shower gel · Comes in a gift bag', 'Shower gel first, then hand cream and body spray to finish.', false, false, 0)
) as v(name, tagline, description, price, compare_at, image, category, badge,
       stock, size, skin_type, benefits, how_to_use, featured, bestseller, reviews)
where not exists (select 1 from products p where p.name = v.name);

select count(*) as total_products from products;
